name: Automated Preprocessing

on:
  push:
    paths:
      - "detection_fraud_dataset.csv"
      - "preprocessing/automate_Rifqi.py"

permissions:
  contents: write

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install libraries
        run: |
          pip install pandas scikit-learn

      - name: Run preprocessing
        run: |
          python preprocessing/automate_Rifqi.py

      - name: Commit processed dataset
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add preprocessing/train_fraud.csv
          git commit -m "auto preprocessing dataset" || echo "No changes to commit"
          git push
